#!/bin/sh

##
# Runit run script for postgresql
#

# If the database has been persisted in a volume, it may need
# permissions setting.
chown -R postgres /var/lib/postgresql/ || exit 1

exec /sbin/setuser postgres /usr/lib/postgresql/11/bin/postgres \
    -D /var/lib/postgresql/11/main \
    -c config_file=/etc/postgresql/11/main/postgresql.conf
